insert into book(id, book_name, author_name, genre) 
values
	(UUID(), 'Hamlet', 'william shakespeare', 'Drama'),
	(UUID(), 'The Catcher in the Rye', 'J.D. Salinger', 'Fiction'),
    (UUID(), 'To Kill a Mockingbird', 'Harper Lee', 'Classics'),
    (UUID(), '1984', 'George Orwell', 'Dystopian'),
    (UUID(), 'The Great Gatsby', 'F. Scott Fitzgerald', 'Classics'),
    (UUID(), 'Pride and Prejudice', 'Jane Austen', 'Romance'),
    (UUID(), 'The Hobbit', 'J.R.R. Tolkien', 'Fantasy'),
    (UUID(), 'Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Fantasy'),
    (UUID(), 'The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy'),
    (UUID(), 'The Hunger Games', 'Suzanne Collins', 'Science Fiction'),
    (UUID(), 'The Da Vinci Code', 'Dan Brown', 'Mystery'),
    (UUID(), 'The Shining', 'Stephen King', 'Horror'),
    (UUID(), 'Brave New World', 'Aldous Huxley', 'Dystopian'),
    (UUID(), 'The Alchemist', 'Paulo Coelho', 'Adventure'),
    (UUID(), 'The Chronicles of Narnia', 'C.S. Lewis', 'Fantasy'),
	(UUID(), 'To Kill a Mockingbird', 'Harper Lee', 'Classics'),
    (UUID(), '1984', 'George Orwell', 'Dystopian'),
    (UUID(), 'The Great Gatsby', 'F. Scott Fitzgerald', 'Classics'),
    (UUID(), 'Pride and Prejudice', 'Jane Austen', 'Romance'),
    (UUID(), 'The Hobbit', 'J.R.R. Tolkien', 'Fantasy'),
    (UUID(), 'Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Fantasy'),
    (UUID(), 'The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy'),
    (UUID(), 'The Hunger Games', 'Suzanne Collins', 'Science Fiction'),
    (UUID(), 'The Da Vinci Code', 'Dan Brown', 'Mystery'),
    (UUID(), 'The Shining', 'Stephen King', 'Horror'),
    (UUID(), 'Brave New World', 'Aldous Huxley', 'Dystopian'),
    (UUID(), 'The Alchemist', 'Paulo Coelho', 'Adventure'),
    (UUID(), 'The Chronicles of Narnia', 'C.S. Lewis', 'Fantasy'),
    (UUID(), 'Pride and Prejudice', 'Jane Austen', 'Romance'),
    (UUID(), 'The Hobbit', 'J.R.R. Tolkien', 'Fantasy'),
    (UUID(), 'Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Fantasy'),
    (UUID(), 'The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy'),
    (UUID(), 'The Hunger Games', 'Suzanne Collins', 'Science Fiction'),
    (UUID(), 'The Da Vinci Code', 'Dan Brown', 'Mystery'),
    (UUID(), 'The Shining', 'Stephen King', 'Horror'),
    (UUID(), 'Brave New World', 'Aldous Huxley', 'Dystopian'),
    (UUID(), 'The Alchemist', 'Paulo Coelho', 'Adventure'),
    (UUID(), 'The Chronicles of Narnia', 'C.S. Lewis', 'Fantasy'),
    (UUID(), 'The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy'),
    (UUID(), 'The Hunger Games', 'Suzanne Collins', 'Science Fiction'),
    (UUID(), 'The Da Vinci Code', 'Dan Brown', 'Mystery'),
    (UUID(), 'The Shining', 'Stephen King', 'Horror'),
    (UUID(), 'Brave New World', 'Aldous Huxley', 'Dystopian'),
    (UUID(), 'The Alchemist', 'Paulo Coelho', 'Adventure'),
    (UUID(), 'The Chronicles of Narnia', 'C.S. Lewis', 'Fantasy'),
    (UUID(), 'The Da Vinci Code', 'Dan Brown', 'Mystery'),
    (UUID(), 'The Shining', 'Stephen King', 'Horror'),
    (UUID(), 'Brave New World', 'Aldous Huxley', 'Dystopian'),
    (UUID(), 'The Alchemist', 'Paulo Coelho', 'Adventure'),
    (UUID(), 'The Chronicles of Narnia', 'C.S. Lewis', 'Fantasy'),
    (UUID(), 'Brave New World', 'Aldous Huxley', 'Dystopian'),
    (UUID(), 'The Alchemist', 'Paulo Coelho', 'Adventure'),
    (UUID(), 'The Chronicles of Narnia', 'C.S. Lewis', 'Fantasy'),
    (UUID(), 'The Alchemist', 'Paulo Coelho', 'Adventure'),
    (UUID(), 'The Chronicles of Narnia', 'C.S. Lewis', 'Fantasy'),
    (UUID(), 'The Alchemist', 'Paulo Coelho', 'Adventure'),
    (UUID(), 'The Chronicles of Narnia', 'C.S. Lewis', 'Fantasy');
